parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: appName
  default: ''
- name: buildNumber
  default: ''
- name: linuxFxVersion
  default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:

            - task: AzureWebAppContainer@1
              displayName: '1. Deploy to Stage Slot'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appName: ${{ parameters.appName }}
                deployToSlotOrASE: true
                resourceGroupName: ${{ parameters.resourceGroupName }}
                slotName: staging
                containers: ${{ parameters.linuxFxVersion }}
                appSettings: '-APPLICATION_VERSION ${{ parameters.buildNumber }}'
            
            - task: AzureAppServiceManage@0
              displayName: '2. Swap Slots'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                WebAppName: ${{ parameters.appName }}
                ResourceGroupName: ${{ parameters.resourceGroupName }}
                SourceSlot: staging
