trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-app-service-cicd - BUILD'
  
variables:
  azureSubscription: 'Demo Account'
  dockerRegistryUsername: 'rutzscocr'
stages:
- template: azure-release-pipelines-with-swap-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'CI-APP-SERVICE'
    azureSubscription: ${{ variables.azureSubscription }}
    resourceGroupName: 'rutzsco-app-service-api-ci'
    region: 'East US'
    appName: 'rutzsco-app-service-api-ci'
    buildNumber: $(resources.pipeline.build.runName)
    containerVersion: 'rutzscocr.azurecr.io/demo-api:$(resources.pipeline.build.runName)'
    dockerRegistryUsername: $(dockerRegistryUsername)
    dockerRegistryPassword: $(dockerRegistryPassword)
- template: azure-release-pipelines-with-swap-stage-template.yml
  parameters:
    stageName: 'PROD'
    environment: 'PROD-APP-SERVICE'
    azureSubscription: ${{ variables.azureSubscription }}
    resourceGroupName: 'rutzsco-app-service-api-prod'
    region: 'East US'
    appName: 'rutzsco-app-service-api-prod'
    buildNumber: $(resources.pipeline.build.runName)
    containerVersion: 'rutzscocr.azurecr.io/demo-api:$(resources.pipeline.build.runName)'
    dockerRegistryUsername: $(dockerRegistryUsername)
    dockerRegistryPassword: $(dockerRegistryPassword)