parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: appName
  default: ''
- name: buildNumber
  default: ''
- name: containerVersion
  default: ''
- name: dockerRegistryPassword
  default: ''
- name: dockerRegistryUsername
  default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment:
      environment: ${{ parameters.environment }}
      pool:
        name: 'ubuntu-latest'
      strategy:                   
        blueGreen:    
          preDeploy:
            steps:
            - script: echo initialize, cleanup, install certs...
          deploy:              
            steps:                                   
            - script: echo deploy app updates... 
          routeTraffic:
            delay: 60m
            steps:
            - script: echo route traffic...   
          postRouteTaffic:
            pool: server       # lifecycle job pool type
            steps:          
            - script: echo monitor app health        
          on:
            failure:
              steps:
              - script: echo rollback, cleanup..     
            success:
              steps:
              - script: echo checks passed...
